# Generated by Django 6.0.6 on 2026-07-08 07:25

import django.db.models.deletion
import reports.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('employee_register', 'Employee Leave Register'), ('monthly_attendance', 'Monthly Attendance Report'), ('leave_utilization', 'Leave Utilization Report'), ('compliance', 'Compliance Report'), ('audit_trail', 'Audit Trail Report')], max_length=40)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=reports.models.report_upload_path)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('employee_register', 'Employee Leave Register'), ('monthly_attendance', 'Monthly Attendance Report'), ('leave_utilization', 'Leave Utilization Report'), ('compliance', 'Compliance Report'), ('audit_trail', 'Audit Trail Report')], max_length=40)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('cron_expression', models.CharField(default='@daily', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['report_type'],
            },
        ),
    ]
