# Generated by Django 6.0.6 on 2026-07-08 07:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('MEMO_ASSIGNED_TO_REVIEW', 'Memo assigned to review'), ('MEMO_APPROVED', 'Memo approved'), ('MEMO_REJECTED', 'Memo rejected'), ('MEMO_RETURNED', 'Memo returned'), ('LEAVE_SUBMITTED', 'Leave submitted'), ('LEAVE_APPROVED', 'Leave approved'), ('LEAVE_REJECTED', 'Leave rejected'), ('LEAVE_BALANCE_LOW', 'Leave balance low'), ('POLICY_UPDATED', 'Policy updated'), ('SYSTEM_ANNOUNCEMENT', 'System announcement'), ('WEEKLY_DIGEST', 'Weekly digest')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('action_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('recipient', 'idempotency_key'), name='uniq_notification_idempotency')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('MEMO_ASSIGNED_TO_REVIEW', 'Memo assigned to review'), ('MEMO_APPROVED', 'Memo approved'), ('MEMO_REJECTED', 'Memo rejected'), ('MEMO_RETURNED', 'Memo returned'), ('LEAVE_SUBMITTED', 'Leave submitted'), ('LEAVE_APPROVED', 'Leave approved'), ('LEAVE_REJECTED', 'Leave rejected'), ('LEAVE_BALANCE_LOW', 'Leave balance low'), ('POLICY_UPDATED', 'Policy updated'), ('SYSTEM_ANNOUNCEMENT', 'System announcement'), ('WEEKLY_DIGEST', 'Weekly digest')], max_length=40)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'category'), name='uniq_user_category_pref')],
            },
        ),
    ]
