# Generated by Django 6.0.6 on 2026-07-08 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0002_memotemplate_created_at_memotemplate_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='current_reviewer',
            field=models.ForeignKey(blank=True, help_text="The user assigned as CHECKER for this memo. Displayed as 'Checker' in the UI. Field kept as 'current_reviewer' to avoid a rename migration.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memos_to_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
