# Generated by Django 6.0.6 on 2026-07-09 09:42
import re

from django.db import migrations, models

_NUMBER = re.compile(r"^NIFN-([A-Z]+)-(\d{4})-(\d+)$")


def seed_sequences(apps, schema_editor):
    """
    Initialize the counter from existing memo numbers so newly generated
    numbers continue the sequence instead of colliding with issued ones.
    """
    Memo = apps.get_model("memos", "Memo")
    Sequence = apps.get_model("memos", "MemoNumberSequence")
    maxima = {}
    for number in Memo.objects.values_list("memo_number", flat=True):
        match = _NUMBER.match(number or "")
        if not match:
            continue
        code, year, seq = match.group(1), int(match.group(2)), int(match.group(3))
        key = (code, year)
        if seq > maxima.get(key, 0):
            maxima[key] = seq
    for (code, year), value in maxima.items():
        Sequence.objects.update_or_create(
            type_code=code, year=year, defaults={"last_value": value}
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0005_alter_memo_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=8)),
                ('year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('type_code', 'year')},
            },
        ),
        migrations.RunPython(seed_sequences, noop),
    ]
