# Generated by Django 6.0.6 on 2026-07-08 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('doc_type', models.CharField(choices=[('memo', 'Memo'), ('leave_application', 'Leave Application'), ('leave_certificate', 'Leave Certificate')], max_length=30)),
                ('target_type', models.CharField(max_length=30)),
                ('target_id', models.UUIDField()),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('actors', models.JSONField(blank=True, default=list)),
                ('is_valid', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
